version: 2
jobs:
  build:
    docker:
      - image: circleci/clojure:openjdk-11-tools-deps
    steps:
      - checkout
      - restore_cache:
          key: nipper-{{ checksum "deps.edn" }}
      - run: ./test.sh
